server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: naruto
    password: naruto

keycloak:
  realm: master
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  resource: spring-app
  bearer-only: true
